spring.application.name=techstore-secure-app

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/techstore_secure
spring.datasource.username=postgres
spring.datasource.password=Pa55w.rd

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=admin
spring.security.user.password=Pa55w.rd

jwt.secret=TechStoreSecureAppJwtSecretKey2026VerySecureForAcademicUse123456
jwt.expiration-ms=3600000